# fly.toml app configuration file generated for smartbot1 on 2023-07-05T12:13:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartbot1"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
